version: '3'

services:
  dev:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./dev-config:/root/.config
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      - DISPLAY=${DISPLAY}
    networks:
      - clipboard-network
    tty: true
    stdin_open: true

  clipboard:
    build:
      context: .
      dockerfile: Dockerfile.clipboard
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - $HOME/.Xauthority:/root/.Xauthority:ro
    environment:
      - DISPLAY=${DISPLAY}
      - XAUTHORITY=/root/.Xauthority
    networks:
      - clipboard-network

networks:
  clipboard-network:
    driver: bridge

