FROM ubuntu:latest

RUN apt-get update && apt-get install -y \
    neovim \
    tmux \
    netcat-openbsd \
    ncurses-term \
    && rm -rf /var/lib/apt/lists/*

ENV DEBIAN_FRONTEND=noninteractive
ENV TERM=xterm-256color

WORKDIR /root

# Change the CMD to keep the container running
CMD ["tail", "-f", "/dev/null"]
