FROM golang:1.20 as builder

# Install Clipper
RUN go install github.com/wincent/clipper@latest

FROM ubuntu:latest

# Copy the Clipper binary from the builder stage
COPY --from=builder /go/bin/clipper /usr/local/bin/clipper

# Copy the start script and config file
COPY start-clipper.sh /usr/local/bin/start-clipper.sh
COPY clipper.json /root/.config/clipper/clipper.json

RUN chmod +x /usr/local/bin/start-clipper.sh

ENTRYPOINT ["/usr/local/bin/start-clipper.sh"]
CMD ["/bin/bash"]
