FROM python:3.9-slim

RUN apt-get update && apt-get install -y \
    xclip \
    x11-apps \
    xsel

COPY clipboard_service.py /app/clipboard_service.py

WORKDIR /app

CMD ["python", "clipboard_service.py"]
